bot/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views.index import *
from .views.chattbot import *


app_name='bot'
urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^chatbot/$', ChatterBotAppView.as_view(), name='main'),
    url(r'^api/chatterbot/', ChatterBotApiView.as_view(), name='chatterbot'),
]

freechatbot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bot.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

main/models.py
from django.db import models

# Create your models here.

bot/views/chattbot.py
import json
from django.views.generic.base import TemplateView
from django.views.generic import View
from django.http import JsonResponse
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.utils import timezone as dt
import spacy



class ChatterBotAppView(TemplateView):
    template_name = 'bot/app.html'

    def get_context_data(self, **kwargs):
        tz = 8
        if dt.now().hour+tz > 0 and dt.now().hour+tz <= 11 :
            greeting = 'Good Morning'
        elif dt.now().hour+tz >=12 and dt.now().hour+tz < 15:
            greeting = 'Good Afternoon'
        elif dt.now().hour+tz >=18 and dt.now().hour+tz < 24:
            greeting = 'Good Evening'
        else:
            greeting = 'Hello'

        data = super(ChatterBotAppView, self).get_context_data(**kwargs)
        if self.request.user.is_anonymous:
            data['greeting'] = 'bot: {},What can I help you? '.format(greeting)
        else:
            data['greeting'] = 'bot: {} {}, What can I help you? '.format(greeting,self.request.user)
        return data


@method_decorator(csrf_exempt, name='dispatch')
class ChatterBotApiView(View):
    """
    Provide an API endpoint to interact with ChatterBot.
    """


    chatterbot = ChatBot(**settings.CHATTERBOT)


    def post(self, request, *args, **kwargs):
        input_data = json.loads(request.body.decode('utf-8'))

        if 'text' not in input_data:
            return JsonResponse({
                'text': [
                    'The attribute "text" is required.'
                ]
            }, status=400)

        response = self.chatterbot.get_response(input_data)
        response_data = response.serialize()
        return JsonResponse(response_data, status=200)

    def get(self, request, *args, **kwargs):

        return JsonResponse({
            'name': self.chatterbot.name
        })

bot/views/index.py
from django.shortcuts import render

def index(request):
    template = 'bot/index.html'
    context = {}

    return render(request, template, context)
    # return HttpResponseRedirect('/tas/list/')

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.

bot/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--meta http-equiv="refresh" content="900"/-->
    {% block meta %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.jqueryui.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}"/>

    <!-- Latest compiled and minified CSS  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">

    {% block style %} {% endblock %}
    <style>.beta-ribbon {
                z-index: 80;
                text-transform: uppercase;
                font-weight: 800;
                font-size: 8px;
                width: 110px;

                background: #50bcb6;
                position: absolute;
                top: 0px;
                right: -35px;
                text-align: center;
                line-height: 30px;
                letter-spacing: 1px;
                color: #f0f0f0;
                transform: rotate(30deg); }</style>
    <!--[if lt IE 9]-->
    <script src="{% static 'js/html5shiv.min.js'%}"></script>
    <script src="{% static 'js/respond.min.js'%}"></script>
    <!--for altair chart display -->
    <script src="{% static 'js/vega_3.2.js' %}"></script>
    <script src="{% static 'js/vega_lit_2.4.1.js' %}"></script>
    <script src="{% static 'js/vega_embed_3.0.js' %}"></script>

    <!--[endif]-->

</head>

<body>


<div class="container">

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="beta-ribbon top-right sticky blue"
             style="font-weight: bold; font-size: 6px;font-family: 'Noto Sans', sans-serif;z-index:9999; ">
             Prototype
        </div>

        <div class="container-fluid">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="#">FreeChatBot</a>


            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a lass="dropdown-toggle" href="{% url 'bot:main' %}">Chat</a></li>
                        <!--li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Shop<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="">Order</a></li>
                                <li><a href="">Search</a></li>
                            </ul>
                        </li-->

                        <!--li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Report<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="">Analysis</a></li>
                            </ul>
                        </li-->

                </ul>

            </div>

        </div>

    </nav>
</div>
<div class="container col-xl-12 col-lg-12 col-12 col-md-12 col-sm-12" style="margin: 10 auto; width: 98%; !important">
    {% block body_block %}{% endblock %}
    {% block content %}{% endblock %}
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/js.cookie.js' %}"></script>

<script src="{% static 'js/datatable.js' %}"></script>
<script src="{% static 'js/ajax.js' %}"></script>
<script src="{% static 'js/bootstrap-tab.js' %}"></script>


<script>
    $(document).ready(function() {
        $( document ).on('click',".nav.navbar-nav li",function() {
               $( this ).addClass( 'active' );
            } );
        });

</script>
<script> {% block script %} {% endblock %}</script>
</body>
</html>

bot/templates/bot/app.html
{% extends "base.html" %}
{% load static %}

{% block title %}bot{% endblock %}
{% block content %}


<div class="container">
    <h3 class="jumbotron-heading text-md-center">ChatBot Demo</h3>
    <p class="lead text-md-center">
        Type something to talk with the Bot.
    </p>
    <div class="jumbotron mt-1">

        <div class="row">
            <div class="col-md-6 offset-md-3">
                <ul class="list-group chat-log js-chat-log">
                    <li class="list-group-item">{{greeting}}</li>
                </ul>
            </div>
        </div>

    </div>
    <div class="input-group input-group-md mt-1">
        <input type="text" class="form-control js-text" placeholder="Type your message here..."/>
        <span class="input-group-btn">
                        <button class="btn btn-primary js-say">Submit</button>
                    </span>
    </div>

</div>

{% endblock %}

{% block script %}
    var chatterbotUrl = '{% url "bot:chatterbot" %}';
    const csrftoken = Cookies.get('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

    var $chatlog = $('.js-chat-log');
    var $input = $('.js-text');
    var $sayButton = $('.js-say');

    function createRow(text) {
        var $row = $('<li class="list-group-item"></li>');

        $row.text(text);
        $chatlog.append($row);
        }

    function submitInput() {
        var inputData = {
            'text': $input.val()
            }

        // Display the user's input on the web page
        createRow('You: ' + inputData.text);

        var $submit = $.ajax({
            type: 'POST',
            url: chatterbotUrl,
            data: JSON.stringify(inputData),
            contentType: 'application/json'
            });

        $submit.done(function(statement) {
            createRow('bot: ' + statement.text);

            // Clear the input field
            $input.val('');

            // Scroll to the bottom of the chat interface
            $chatlog[0].scrollTop = $chatlog[0].scrollHeight;
            });

        $submit.fail(function() {
            // TODO: Handle errors
            });
        }

      $sayButton.click(function() {
        submitInput();
        });

    $input.keydown(function(event) {
        // Submit the input when the enter button is pressed
        if (event.keyCode == 13) {
            submitInput();
            }
        });
{% endblock %}

bot/templates/bot/index.html
{% extends "base.html" %}

{% block title %}home{% endblock %}
{% block content %}
<h2>
    {%if request.user.username %}
        Hello, {{request.user.username}}! <br/>
        Wellcome!
    {%else%}
        Hello, Stranger ^^! <br/>
        What can i help you?
    {%endif%}

</h2>


{% endblock %}

main/templates/main/access_denial.html
{% extends "base.html" %}


{% block title %}{% endblock %}
{% block content %}
<h2>Access Denial</h2>
{% endblock %}